sudo: false
os: linux
dist: trusty
language: php
php:
- 7.1
- 7.2
- nightly

matrix:
  allow_failures:
  - php: nightly

branches:
  only:
  - master

install:
- composer install --prefer-dist

script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit

cache:
  directories:
  - $HOME/.composer/cache/files
  - vendor
