sudo: false
os: linux
dist: trusty
language: php
php:
- 5.6
- 7.0
- 7.1

branches:
  only:
  - master

install:
- composer install --prefer-dist

script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit

cache:
  directories:
  - $HOME/.composer/cache/files
  - vendor
